sonar.projectKey=tienda-online-fs3-jacob
sonar.projectName=Tienda Online FullStack III
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=frontend-tienda-angular/src/app,ms-usuarios/src/main/java,ms-productos/src/main/java,ms-gestion-productos/src/main/java
sonar.tests=frontend-tienda-angular/src/app,ms-usuarios/src/test/java,ms-productos/src/test/java,ms-gestion-productos/src/test/java
sonar.test.inclusions=**/*.spec.ts,**/src/test/java/**/*.java
sonar.exclusions=**/*.spec.ts,frontend-tienda-angular/src/main.ts,frontend-tienda-angular/src/app/app.routes.ts,frontend-tienda-angular/src/app/config/**,**/*Application.java
sonar.coverage.exclusions=**/*Application.java,**/model/**,**/dto/**,**/repository/**,**/exception/ErrorDetails.java

sonar.javascript.lcov.reportPaths=frontend-tienda-angular/coverage/frontend-tienda-angular/lcov.info
sonar.java.binaries=ms-usuarios/target/classes,ms-productos/target/classes,ms-gestion-productos/target/classes
sonar.coverage.jacoco.xmlReportPaths=ms-usuarios/target/site/jacoco/jacoco.xml,ms-productos/target/site/jacoco/jacoco.xml,ms-gestion-productos/target/site/jacoco/jacoco.xml
