spring.application.name=ms-usuarios
server.port=8081

# Configura estos valores con tu instancia Oracle
spring.datasource.url=jdbc:oracle:thin:@//host.docker.internal:1521/FREEPDB1
spring.datasource.username=TIENDA
spring.datasource.password=Tienda1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.open-in-view=false
